name: Build Nym Validator Rewarder

on:
  workflow_dispatch:

env:
  NETWORK: mainnet

jobs:
  publish-nym:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: arc-ubuntu-22.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
      RUSTUP_PERMIT_COPY_RENAME: 1
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: nymtech/nym
          ref: tmp/precommit-store-fix 

      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get -y install ripgrep libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libudev-dev squashfs-tools
        continue-on-error: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build all binaries
        run: cargo build --bin nym-validator-rewarder --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nym-validator-rewarder-artifact
          path: |
            target/release/nym-validator-rewarder
          retention-days: 30 
