name: Build credential proxy

on:
  workflow_dispatch:
    inputs:
      ref:
        required: false
        description: Branch or tag to checkout from `nymtech/nym` repository
        default: develop
        
env:
  NETWORK: mainnet

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04-16-core,ubuntu-24.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get -y install ripgrep build-essential curl wget libssl-dev libgtk-3-dev libudev-dev squashfs-tools
        continue-on-error: true

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: nymtech/nym
          ref: ${{ inputs.ref }}

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        run: cd nym-credential-proxy/nym-credential-proxy && cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-${{ matrix.platform }}
          path: |
            nym-credential-proxy/target/release/nym-credential-proxy
          retention-days: 30
