name: Build Nym-Node (otel)

on:
  workflow_dispatch:


jobs:
  publish-nym:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get -y install ripgrep libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libudev-dev squashfs-tools
        continue-on-error: true

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: nymtech/nym
          ref: feature/otel

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build all binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin nym-node --release --features otel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            target/release/nym-node
          retention-days: 30

      - name: Prepare build output directory
        shell: bash
        env:
          OUTPUT_DIR: ci-builds/nym-node/feature/otel
        run: |
          rm -rf ci-builds || true
          mkdir -p $OUTPUT_DIR
          echo $OUTPUT_DIR

      - name: Prepare build output
        shell: bash
        env:
          OUTPUT_DIR: ci-builds/nym-node/feature/otel
        run: |
          cp target/release/nym-node $OUTPUT_DIR

      - name: Deploy branch to CI www
        continue-on-error: true
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_WWW_SSH_PRIVATE_KEY }}
          ARGS: "-avzr"
          SOURCE: "ci-builds/"
          REMOTE_HOST: ${{ secrets.CI_WWW_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.CI_WWW_REMOTE_USER }}
          TARGET: ${{ secrets.CI_WWW_REMOTE_TARGET }}/builds/
          EXCLUDE: "/dist/, /node_modules/"          
